### ISSUE TITLE
Error Creating Release package

### ISSUE THREAD

**Issue by Dangerous-Mind** [estruyf/vscode-spfx-task-runner#2]
When I try to create a release package I receive the following messages for each of the commands.

```
Executing task: "C:\Users\MyName(CompanyName)\AppData\Roaming\npm\gulp.cmd" package-solution --ship <

CompanyName: The term 'CompanyName' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:21
+ C:\Users\MyName(CompanyName)\AppData\Roaming\npm\gulp.cmd package-sol ...
+                     ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (CompanyName:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

After talking to vscode I was advised to talk to the owner of the plugin to see if you can escape the chars on the path (the brackets can be escaped by the char ' ).
` "C:\Users\MyName´(CompanyName´)\AppData\Roaming\npm\gulp.cmd" package-solution --ship 
`

The issue reported to VScode is:
[https://github.com/Microsoft/vscode/issues/70509](https://github.com/Microsoft/vscode/issues/70509)

Can you please check? 
Thanks

**Comment by estruyf** [comment]
I'll work on it. Thanks for reporting this.

**Comment by estruyf** [comment]
I have published a fix for this, would you be able to test it out? @Dangerous-Mind

**Comment by Dangerous-Mind** [comment]
I teste it and it gives the same error.
There is no escape char on the command.

> Executing task: "C:\Users\myname(CompanyName)\AppData\Roaming\npm\gulp.cmd" package-solution --ship

**Comment by Dangerous-Mind** [comment]
The replace command should be used on the gulpCommand and not on the rootfolder.
Or in both. I didn't check the rest of the code. 
But you are using it to run the task (vscode.ShellExecution(`${gulpCommand} bundle`))

```
let gulpCommand = gulpCmd && gulpCmd.executePath ? gulpCmd.executePath : "gulp";
gulpCommand = gulpCommand && gulpCommand.includes("(") ? gulpCommand.replace(/\(/g, "`(") : gulpCommand;
gulpCommand = gulpCommand && gulpCommand.includes(")") ? gulpCommand.replace(/\)/g, "`)") : gulpCommand;

let rootFolder = gulpCmd && gulpCmd.folderPath ? gulpCmd.folderPath : vscode.workspace.rootPath;
if (process && process.platform && process.platform.toLowerCase() === "windows") {
// Escape the command path
rootFolder = rootFolder && rootFolder.includes("(") ? rootFolder.replace(/\(/g, "`(") : rootFolder;
rootFolder = rootFolder && rootFolder.includes(")") ? rootFolder.replace(/\)/g, "`)") : rootFolder;
}
```

**Comment by estruyf** [comment]
New version is publishing, feel free to test it out.

**Comment by Dangerous-Mind** [comment]
Hi,

Nop. It stopped working with the new update (I had made the change to your code directly).

Probably it doesn't enter the if: 
`if  (process && process.platform && process.platform.toLowerCase() === "windows")`

It started working after moving the command outside the if
```
gulpCommand = gulpCommand && gulpCommand.includes("(") ? gulpCommand.replace(/\(/g, "`(") : gulpCommand;
gulpCommand = gulpCommand && gulpCommand.includes(")") ? gulpCommand.replace(/\)/g, "`)") : gulpCommand;
```

**Comment by estruyf** [comment]
Would you be able to debug? Can you check if the **platform** value you retrieve is **windows**?

**Comment by Dangerous-Mind** [comment]
I've tried but I'm not that good at powershell. 
I know I'll have to learn it someday but I've been postponing it for some years now. 

How can I write a log file on the line before the if  with the process.platform.toLowerCase()?

By the way. My change makes the debug "gulp package-solution" run two times. 
One without --Ship and another with --ship.

**Comment by Dangerous-Mind** [comment]
New version also not working. (the code was commented)

**Comment by estruyf** [comment]
I know, the new version is going back to the original code. Right now this issue is stuck, as I cannot reproduce it with an identical setup like yours.

If you would be able to run a debug build on your machine, that would help a lot. 

- Clone this repo
- Open the project in Visual Studio Code
- Run an `npm install`
- Press `F5` and you should be able to run the debug build + it will open another VSCode window in which you can test out the extension.

**Comment by Dangerous-Mind** [comment]
I didn't remembered to get it that way. :)

Done.
The process.platform value is "win32"

**Comment by Dangerous-Mind** [comment]
I could have checked on node.js command prompt also.

[node JS Documentation](https://nodejs.org/api/process.html#process_process_platform)

> The process.platform property returns a string identifying the operating system platform on which the Node.js process is running.
> 
> Currently possible values are:
> 'aix'
> 'darwin'
> 'freebsd'
> 'linux'
> 'openbsd'
> 'sunos'
> 'win32'
>

**Comment by estruyf** [comment]
The `win32` check has now been implemented.

**Comment by Dangerous-Mind** [comment]
Looking good now.

Thanks @estruyf  :)
